sudo: false
language: php


php:
  # Versions of PHP you want your project run with.
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
  
env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable


before_install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - composer clear-cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer update --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  

after_script:
    
